// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCl-0FFlk9NSu_wFFKJW4gqkii2CNRTxpg',
    appId: '1:1039841495298:web:31af0e8e3d0f64c5929a1b',
    messagingSenderId: '1039841495298',
    projectId: 'investtechapp',
    authDomain: 'investtechapp.firebaseapp.com',
    databaseURL: 'https://investtechapp.firebaseio.com',
    storageBucket: 'investtechapp.appspot.com',
    measurementId: 'G-QCPTWPQ21F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZ2budyHwbHM9R02GXrqX7pcSEFiyJd_Q',
    appId: '1:1039841495298:android:4f87df8b400075cb929a1b',
    messagingSenderId: '1039841495298',
    projectId: 'investtechapp',
    databaseURL: 'https://investtechapp.firebaseio.com',
    storageBucket: 'investtechapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCtrvsEcLqlm_jam8VsUfKthmJwzxPqTU',
    appId: '1:1039841495298:ios:330d99a7b9f0025a929a1b',
    messagingSenderId: '1039841495298',
    projectId: 'investtechapp',
    databaseURL: 'https://investtechapp.firebaseio.com',
    storageBucket: 'investtechapp.appspot.com',
    androidClientId: '1039841495298-46nk41a36m7efii4r72802vkhfjfqcfl.apps.googleusercontent.com',
    iosClientId: '1039841495298-4vsmteitj5b7ggchvsrvq1kkpjcteag7.apps.googleusercontent.com',
    iosBundleId: 'com.example.investtechApp',
  );
}
